api:
  name: "Simple_Post_App_API"
  security:
    token:
      secret: "${JWT_SECRET}"

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/simplepostapp?useSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true